### PR TITLE
fix for iOS >= 15.4 (cam preview not visible)

### PR DESCRIPTION
**Pull request by fabioz23**
fix for iOS >= 15.4 (cam preview not visible)

### CODE REVIEW

**Comment by phausero** [comment]
Looking good to me. You could go the safe route by also setting the isOpaque property of the scrollView. Also, makeOpaque function is doing the wrong thing. You could easily fix this in here so hide() work too.

**Comment by v1934** [comment]
I wonder what the original author of cordova-plugin-qrscanner had on mind, that the opacity wasn't actually being reset after hiding for both Android and iOS.
```
@objc func makeOpaque(){
        self.webView?.isOpaque = false
        self.webView?.backgroundColor = UIColor.clear
    }```

```
@objc func show(_ command: CDVInvokedUrlCommand) {
        self.webView?.isOpaque = false
        self.webView?.backgroundColor = UIColor.clear
        self.getStatus(command)
    }
```

Why even bother making 2 different methods that are the same? I'm thinking of fixing this along with this PR, but maybe there was some reasoning for that?

**Comment by phausero** [comment]
I think this is a mistake and there already is a PR to fix this because makeOpaque() is doing the opposite of what it should do. https://github.com/bitpay/cordova-plugin-qrscanner/pull/351/files

**Comment by fabioz23** [comment]
@phausero i've inserted on this PR some changes from PR 351 from the abandoned repo and another fix related to camera selection (was using a deprecated method)

**Comment by fabioz23** [comment]
@v1934 can you check if the same mistake is present on Android side?

**Comment by v1934** [comment]
It was, but I have fixed it in https://github.com/v1934/cordova-plugin-qrscanner-11/commit/aa0f9dd2924e76fb7f4b4aab8c628c17052d7efb#diff-52338800f13fca00cf795e162fb193f92026ea81ba418b56546af376f8cb904e

Looks good to me, I'll merge this PR and push a new release to npm later

**Pull request merged**
